In [1]:
import pandas as pd
import numpy as np
from statistics import *
from scipy.stats import *
from math import *

In [2]:
#loading the data 
# Load the data

weeklyReturn=pd.read_excel("/Users/dantoni/HW6/TP6.xls", skiprows = 4)
weeklyReturn = weeklyReturn.drop([0])
weeklyReturn = weeklyReturn.drop('Name', axis=1)
weeklyReturn = weeklyReturn.astype(float)
names_company = weeklyReturn.columns

df = pd.DataFrame(weeklyReturn, columns = ['AMER.EXPRESS' ,'AOL TIME WARNER', 'AT & T' , 'BLACK & DECKER', 'COLGATE - PALM.', 'FORD MOTOR','MCDONALDS','PFIZER','TEXAS INSTS.','WAL MART STORES'])
#df = df.drop(df.index[0])
df

,AMER.EXPRESS,AOL TIME WARNER,AT & T,BLACK & DECKER,COLGATE - PALM.,FORD MOTOR,MCDONALDS,PFIZER,TEXAS INSTS.,WAL MART STORES
1,-0.043800,0.085714,0.020814,0.030598,0.019958,0.033304,0.075340,0.048667,0.000717,-0.012703
2,0.016129,0.110048,-0.013002,0.002269,0.002762,-0.018660,0.135428,0.056262,0.010036,0.021713
3,0.133016,-0.009698,-0.007485,-0.014151,-0.015840,0.109767,-0.011132,-0.004514,-0.069553,0.000000
4,-0.043990,0.023939,0.003620,-0.009569,-0.038488,0.059969,-0.009006,0.014510,0.110603,0.034238
5,0.006741,-0.053135,-0.068831,0.000000,0.083455,-0.077884,-0.052580,0.146007,0.068681,-0.022451
...,...,...,...,...,...,...,...,...,...,...
239,0.163823,0.082969,0.103357,0.112846,0.006323,0.117105,0.038439,0.092395,0.210563,0.071456
240,-0.045161,0.173387,0.049640,0.052286,-0.005386,0.043581,0.049355,-0.066565,-0.151251,0.020604
241,0.117015,0.013746,-0.005339,0.005808,-0.007581,-0.045147,-0.032068,0.039254,0.087046,-0.051709
242,-0.023921,0.041356,0.046779,-0.013045,-0.020735,0.040189,0.066262,0.056972,-0.056747,0.008403
243,-0.008451,-0.009115,-0.013187,-0.013651,-0.023031,-0.031818,-0.111859,-0.029184,0.009358,0.018148

In [3]:
# Question 1
##Quantile estimation

#American-express 
AmRe = df['AMER.EXPRESS'] 

#AmRe=weeklyReturn.iloc[1:,1]
print(AmRe)
emqu1 = np.quantile(AmRe, 0.05)
emqu2 = np.quantile(AmRe, 0.01)

print(emqu1) #-0.09334706228021589
print(emqu2) #-0.14053384957574752

1     -0.043800
2      0.016129
3      0.133016
4     -0.043990
5      0.006741
         ...
239    0.163823
240   -0.045161
241    0.117015
242   -0.023921
243   -0.008451
Name: AMER.EXPRESS, Length: 243, dtype: float64
-0.09334706228021589
-0.14053384957574752

In [4]:
## Question 2 - VaR estimation

In [5]:
# Ex 2.1: portfolio of our choice 

#we have 10 assets. we will take an equally weight 
a = 1/10 
weights = np.repeat(a,10)

In [6]:
#creating a portfolio 

porto=np.dot(weeklyReturn,weights.T) #dot prodict Y*a'
porto=pd.DataFrame(porto, columns = ['portfolio'])
porto

     portfolio
0     0.025861
1     0.032298
2     0.011041
3     0.014583
4     0.003000
..         ...
238   0.099928
239   0.012049
240   0.012102
241   0.014551
242  -0.021279

[243 rows x 1 columns]

In [7]:
#mean_vector 

individual_means= df.mean(axis = 0,skipna = True) 
print(individual_means)

AMER.EXPRESS       0.002125
AOL TIME WARNER    0.006818
AT & T            -0.001802
BLACK & DECKER     0.001037
COLGATE - PALM.    0.001985
FORD MOTOR        -0.002714
MCDONALDS         -0.000633
PFIZER             0.001445
TEXAS INSTS.       0.003713
WAL MART STORES    0.004473
dtype: float64

In [8]:
#variance-covariace matrix 

#short way 

var_cov= df.cov()
print(var_cov) 

#there is a mistake bsc in the diagonal we have entries different from 1 
#doesn't work 

#long way
#assets = np.array(df['AMER.EXPRESS'], df['AOL TIME WARNER'], df['AT & T'] , df['BLACK & DECKER'], df['COLGATE - PALM.'], df['FORD MOTOR'],df['MCDONALDS'],df['PFIZER'],df['TEXAS INSTS.'],df['WAL MART STORES'])

A1=weeklyReturn.iloc[1:,0].values
A2=weeklyReturn.iloc[1:,1].values
A3=weeklyReturn.iloc[1:,2].values
A4=weeklyReturn.iloc[1:,3].values
A5=weeklyReturn.iloc[1:,4].values
A6=weeklyReturn.iloc[1:,5].values
A7=weeklyReturn.iloc[1:,6].values
A8=weeklyReturn.iloc[1:,7].values
A9=weeklyReturn.iloc[1:,8].values
A10=weeklyReturn.iloc[1:,9].values


var_cov1=np.cov(np.array([A1,A2,A3,A4,A5,A6,A7,A8,A9,A10]))
pd.DataFrame(var_cov1, index = names_company, columns = names_company) #same results as above 
#print(var_cov1)

                 AMER.EXPRESS  AOL TIME WARNER    AT & T  BLACK & DECKER  \
AMER.EXPRESS         0.003577         0.002002  0.001275        0.001368
AOL TIME WARNER      0.002002         0.008194  0.002115        0.000926
AT & T               0.001275         0.002115  0.003846        0.000431
BLACK & DECKER       0.001368         0.000926  0.000431        0.003101
COLGATE - PALM.      0.000972         0.000208 -0.000034        0.000768
FORD MOTOR           0.001493         0.001560  0.000832        0.001107
MCDONALDS            0.000864         0.001164  0.000449        0.000757
PFIZER               0.000968         0.001167  0.000317        0.000343
TEXAS INSTS.         0.001806         0.002718  0.001796        0.000951
WAL MART STORES      0.001452         0.001538  0.000930        0.001151

                 COLGATE - PALM.  FORD MOTOR  MCDONALDS    PFIZER  \
AMER.EXPRESS            0.000972    0.001493   0.000864  0.000968
AOL TIME WARNER         0.000208    0.001560   0.001164  0.001167
AT & T                 -0.000034    0.000832   0.000449  0.000317
BLACK & DECKER          0.000768    0.001107   0.000757  0.000343
COLGATE - PALM.         0.002235    0.000434   0.000517  0.000827
FORD MOTOR              0.000434    0.002637   0.000662  0.000491
MCDONALDS               0.000517    0.000662   0.002075  0.000531
PFIZER                  0.000827    0.000491   0.000531  0.002227
TEXAS INSTS.           -0.000140    0.001297   0.000690  0.000341
WAL MART STORES         0.000795    0.000983   0.000546  0.000761

                 TEXAS INSTS.  WAL MART STORES
AMER.EXPRESS         0.001806         0.001452
AOL TIME WARNER      0.002718         0.001538
AT & T               0.001796         0.000930
BLACK & DECKER       0.000951         0.001151
COLGATE - PALM.     -0.000140         0.000795
FORD MOTOR           0.001297         0.000983
MCDONALDS            0.000690         0.000546
PFIZER               0.000341         0.000761
TEXAS INSTS.         0.006745         0.000842
WAL MART STORES      0.000842         0.002521

,AMER.EXPRESS,AOL TIME WARNER,AT & T,BLACK & DECKER,COLGATE - PALM.,FORD MOTOR,MCDONALDS,PFIZER,TEXAS INSTS.,WAL MART STORES
AMER.EXPRESS,0.003583,0.002025,0.001285,0.001379,0.000979,0.001506,0.000882,0.000981,0.001813,0.001454
AOL TIME WARNER,0.002025,0.008202,0.002116,0.000920,0.000203,0.001554,0.001144,0.001156,0.002730,0.001550
AT & T,0.001285,0.002116,0.003860,0.000430,-0.000036,0.000832,0.000444,0.000314,0.001804,0.000936
BLACK & DECKER,0.001379,0.000920,0.000430,0.003110,0.000769,0.001107,0.000751,0.000338,0.000956,0.001158
COLGATE - PALM.,0.000979,0.000203,-0.000036,0.000769,0.002243,0.000433,0.000514,0.000826,-0.000140,0.000799
FORD MOTOR,0.001506,0.001554,0.000832,0.001107,0.000433,0.002642,0.000654,0.000486,0.001303,0.000990
MCDONALDS,0.000882,0.001144,0.000444,0.000751,0.000514,0.000654,0.002059,0.000518,0.000694,0.000554
PFIZER,0.000981,0.001156,0.000314,0.000338,0.000826,0.000486,0.000518,0.002227,0.000343,0.000767
TEXAS INSTS.,0.001813,0.002730,0.001804,0.000956,-0.000140,0.001303,0.000694,0.000343,0.006773,0.000845
WAL MART STORES,0.001454,0.001550,0.000936,0.001158,0.000799,0.000990,0.000554,0.000767,0.000845,0.002530

In [9]:
#skewness and kurtosis of the portfolio returns.

from scipy import stats

skewness = stats.skew(porto.values)
kurtosis = stats.kurtosis(porto.values)

print(skewness, kurtosis)

[0.06314677] [1.16462838]

In [10]:
#Ex 2.2  Estimate the VaR under the Gaussian hypothesis at the 5% level.

#def gaussianVaR_estimation(obs,aplha): 
#[mu, std] = norm.fit(obs)
#return  (-mean-std*stats.norm.ppf(alpha))
#don't know why it didn't work by using the function 

mu, std = norm.fit(weeklyReturn)
VaR_gaussian= -mu-std*norm.ppf(0.05)

In [11]:
VaR = - np.dot(weights, individual_means.T) - sqrt(np.dot(np.dot(weights, var_cov.T), weights.T))*stats.norm.ppf(0.05)
VaR

0.05606581682634763

In [12]:
# Ex 2.3 using the gaussian kernel, estimate the Var

#first identify the function we are going to minimize in order to get the VaR
def gaussianVaR(VaR, obs, bandwidth, alpha):
    return (np.mean(stats.norm.cdf((-VaR - obs)/bandwidth))-alpha)**2

In [13]:
#minimizing the function 
#obs=porto
#guesses = 1
#nb_obs=len(porto)
#bandwidth= pow(nb_obs, -0.2) * pow(variance(np.reshape(porto.values, 243)), 0.5) #it doesn't work. WHY?
#estimates1 = optimize.fmin(func = gaussianVaR, x0 = guesses, args = (obs, bandwidth, alpha,))

In [14]:
#Dorio's minimization 
import statistics
from scipy import optimize

obs = np.reshape(porto.values, 243) #Q: why do we need to re-shape it?
bandwidth = pow(len(porto), -0.2) * pow(statistics.variance(np.reshape(porto.values, 243)), 0.5)
alpha = 0.05
guesses = -0.2

estimates_Var = optimize.fmin(func = gaussianVaR, x0 = guesses, args = (obs, bandwidth, alpha,))

#the value of the estimated Var using the non-parametric assumption, gaussial kernel 
estimates_Var[0]

Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 17
         Function evaluations: 34

0.0580468749999995

In [15]:
# VaR estimation - Optional

weights_kurt1 = np.array([np.array([0.2, 0.075, 0.2, 0.075, 0.075, 0.075, 0.075, 0.075, 0.075, 0.075])])
weights_kurt3 = np.array([np.array([0, 0, 0, 0, 0, 0, 0.3879, 0, 0.6121, 0])])
weights_kurt5 = np.array([np.array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0])])

kurt1 = stats.kurtosis(np.dot(weights_kurt1, df.values.T).reshape(243), fisher = False)
kurt3 = stats.kurtosis(np.dot(weights_kurt3, df.values.T).reshape(243), fisher = False)
kurt5 = stats.kurtosis(np.dot(weights_kurt5, df.values.T).reshape(243), fisher = False)

In [16]:
print('First portfolio Kurtosis: ', kurt1, '\nSecond portfolio Kurtosis: ', kurt3, '\nThird portfolio Kurtosis: ', kurt5 )

First portfolio Kurtosis:  3.954532555157238
Second portfolio Kurtosis:  3.000058543899553
Third portfolio Kurtosis:  2.8721412081158753

In [17]:
pf_kurt1 = pd.DataFrame(np.dot(weights_kurt1, df.values.T).T, columns = ['Portfolio'])
pf_kurt3 = pd.DataFrame(np.dot(weights_kurt3, df.values.T).T, columns = ['Portfolio'])
pf_kurt5 = pd.DataFrame(np.dot(weights_kurt5, df.values.T).T, columns = ['Portfolio'])

VaR1 = - np.dot(weights_kurt1, individual_means.T) - sqrt(np.dot(np.dot(weights_kurt1, var_cov.T), weights_kurt1.T))*stats.norm.ppf(0.05)
VaR3 = - np.dot(weights_kurt3, individual_means.T) - sqrt(np.dot(np.dot(weights_kurt3, var_cov.T), weights_kurt3.T))*stats.norm.ppf(0.05)
VaR5 = - np.dot(weights_kurt5, individual_means.T) - sqrt(np.dot(np.dot(weights_kurt5, var_cov.T), weights_kurt5.T))*stats.norm.ppf(0.05)

In [18]:
alpha = 0.05
guesses = -0.2

obs = np.reshape(pf_kurt1.values, 243)
bandwidth = pow(len(pf_kurt1), -0.2) * pow(statistics.variance(np.reshape(pf_kurt1.values, 243)), 0.5)
estimates_Var1 = optimize.fmin(func = gaussianVaR, x0 = guesses, args = (obs, bandwidth, alpha,))

obs = np.reshape(pf_kurt3.values, 243)
bandwidth = pow(len(pf_kurt3), -0.2) * pow(statistics.variance(np.reshape(pf_kurt3.values, 243)), 0.5)
estimates_Var3 = optimize.fmin(func = gaussianVaR, x0 = guesses, args = (obs, bandwidth, alpha,))

obs = np.reshape(pf_kurt5.values, 243)
bandwidth = pow(len(pf_kurt5), -0.2) * pow(statistics.variance(np.reshape(pf_kurt5.values, 243)), 0.5)
estimates_Var5 = optimize.fmin(func = gaussianVaR, x0 = guesses, args = (obs, bandwidth, alpha,))

Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 17
         Function evaluations: 34
Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 17
         Function evaluations: 34
Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 19
         Function evaluations: 38

In [19]:
pd.DataFrame(np.array([VaR1, estimates_Var1, VaR3, estimates_Var3,VaR5, estimates_Var5]).reshape(3,2), index = ['Kurtosis > 3', 'Kurtosis = 3', 'Kurtosis < 3'], columns = ['Normal VaR', 'Kernel VaR '])

              Normal VaR  Kernel VaR
Kurtosis > 3    0.059569     0.062734
Kurtosis = 3    0.090539     0.093516
Kurtosis < 3    0.131376     0.137266

In [20]:
# Question 3 - Sensitivities of VaR.

In [21]:
# Ex 3.1 Estimate the sensitivities in the gaussian case.

#using the close form formula 

import math
#individual mean -> vector with mean of assets
#var_cov -> varaince covariance matrix 
#weights -> vector of weights

VaR_gaussian_derivative = - individual_means -np.dot(var_cov,weights.T) / math.sqrt(np.dot(np.dot(weights, var_cov.T),weights.T)) * stats.norm.ppf(0.05)
VaR_gaussian_derivative

AMER.EXPRESS       0.071833
AOL TIME WARNER    0.094409
AT & T             0.057860
BLACK & DECKER     0.050080
COLGATE - PALM.    0.028872
FORD MOTOR         0.056605
MCDONALDS          0.039339
PFIZER             0.035928
TEXAS INSTS.       0.076203
WAL MART STORES    0.049530
dtype: float64

In [22]:
# Ex 3.2 non-parametric using Kernel Gaussian 

def gaussiankernel(obs_x, obs_y, VaR_hat, bandwidth = None):
    """
    kernel_pdf = gaussiankernel(obs,nb_column,bandwidth)
    
    The function gaussiankernel estimates the density of the distribution underlying the sample with the non-parametric gaussian kernel method.  
    
    Remark:
    - The density is estimated between the min and the max of the sample of observations, for nb_points equidistant points.

    Parameters
    ----------
    obs : array
        a vector of observations 
    nb_column : int
        the number of points where the density is estimated (see the remark) 
    bandwidth : double
        the length of the window (optional argument)
    
    Returns
    -------
    kernel_pdf
        a matrix (2, nb_points) where the first row contains the estimation points and the second row contains the values of the density. 

    """

    # the following calculations require obs to be an one-column array.
    if not isinstance(obs_x, np.ndarray):
        print('Error: please transfer the input variable to an array first!')
    if not isinstance(obs_y, np.ndarray):
        print('Error: please transfer the input variable to an array first!')
    #if obs_x.ndim != 1:
    #    print('Error: please transfer the input variable to an one-dimensional array!')

    nb_obs = len(obs_x)
    nb_column = obs_y.shape[1]
    
    # The 3rd input argument of the function gaussiankernel is optional.
    # If no value is passed for the bandwith, the program will a "rule of thumb" value: (https://en.wikipedia.org/wiki/Kernel_density_estimation)
    if bandwidth is None:
        bandwidth = pow(nb_obs, -0.2) * pow(statistics.variance(obs_x.reshape(243)), 0.5)
        

    # We calculate all the points in one step by using the functions mean and the kronecker product.
    # This is the most compact and efficient writing as it optimizes the use of the preprogrammed functions. You should "vectorize" the code at best to obtain a good performance.
    # Check the help on different functions for more details.

    x = (np.outer(obs_x, np.ones(nb_column)) + VaR_hat)/bandwidth
    k = np.exp(-0.5*np.power(x, 2))/np.power(2*math.pi,0.5)
    y = obs_y
    f_above = np.mean((-y*k), axis = 0)/bandwidth
    f_below = np.mean(k, axis=0)/bandwidth
    f = f_above/f_below
    kernel_pdf = f
    
    # Slow way: 
#     def calc_kernel(obs, x, bandwidth):
#        return mean(np.exp((-0.5)*np.power((obs - x)/bandwidth, 2)))/bandwidth/np.power(2*pi,0.5)
#     f = np.array([calc_kernel(obs, x, bandwidth) for x in kernel_pdf])

    return np.array([kernel_pdf])

In [23]:
obs_x = porto.values
obs_y = df.values
VaR_hat = estimates_Var

In [24]:
FOC1 = gaussiankernel(obs_x, obs_y, VaR_hat)

In [25]:
pd.DataFrame(np.array([VaR_gaussian_derivative.values.reshape(10), FOC1.reshape(10)]).T, index = names_company, columns = ['Normal FOC', 'Kernel FOC '])

                 Normal FOC  Kernel FOC
AMER.EXPRESS       0.071833     0.066372
AOL TIME WARNER    0.094409     0.087888
AT & T             0.057860     0.059784
BLACK & DECKER     0.050080     0.042863
COLGATE - PALM.    0.028872     0.023658
FORD MOTOR         0.056605     0.048324
MCDONALDS          0.039339     0.039191
PFIZER             0.035928     0.038356
TEXAS INSTS.       0.076203     0.055747
WAL MART STORES    0.049530     0.048673

In [26]:
## Question 4 - Comparison with mean-variance optimization

def min_var(weight, obj):
    return np.dot(np.dot(weight, var_cov.T), weight.T)

def min_VaR(weight, obj):
    return - np.dot(weight, individual_means.T) - math.sqrt(np.dot(np.dot(weight, var_cov.T), weight.T)) * stats.norm.ppf(0.05)

def constr(weight):
    return sum(weight) - 1

def constr1(weight):
    return np.dot(weight, individual_means.T) - obj

In [27]:
# Ex 4.1

guesses = np.array([np.repeat(0.1,10)])
obj = 0.05
# bnds = np.array(((0,1),)*10)
cons = [{'type':'eq', 'fun': constr},
        {'type':'eq', 'fun': constr1}]

opt_weight = optimize.minimize(min_var, x0 = guesses, constraints=cons, args = (obj,))

In [28]:
# Ex 4.2

guesses = np.array([np.repeat(0.1,10)])
obj = 0.05
# bnds = np.array(((0,1),)*10)
cons = [{'type':'eq', 'fun': constr},
        {'type':'eq', 'fun': constr1}]

opt_weight2 = optimize.minimize(min_VaR, x0 = guesses,constraints = cons, args = (obj,))

In [29]:
pd.DataFrame(np.array([opt_weight.x ,opt_weight2.x]).T, index = names_company, columns = ['Variance Weights', 'VaR Weights'])

                 Variance Weights  VaR Weights
AMER.EXPRESS             0.503727     0.472200
AOL TIME WARNER          1.667726     1.659891
AT & T                  -2.014054    -2.074609
BLACK & DECKER           0.063238     0.037133
COLGATE - PALM.          1.260279     1.229583
FORD MOTOR              -3.812319    -3.779030
MCDONALDS               -1.334333    -1.216435
PFIZER                  -0.063520    -0.147484
TEXAS INSTS.             1.167979     1.187441
WAL MART STORES          3.561277     3.631311

In [30]:
# Same as befor but with weights bounded between 0 and 1

guesses = np.array([np.repeat(0.1,10)])
obj = 0.05
bnds = np.array(((0,1),)*10)
cons = [{'type':'eq', 'fun': constr},
        {'type':'eq', 'fun': constr1}]

opt_weight3 = optimize.minimize(min_var, x0 = guesses, constraints=cons, bounds = bnds,args = (obj,))

In [31]:
# Same as befor but with weights bounded between 0 and 1

guesses = np.array([np.repeat(0.1,10)])
obj = 0.05
bnds = np.array(((0,1),)*10)
cons = [{'type':'eq', 'fun': constr},
        {'type':'eq', 'fun': constr1}]

opt_weight4 = optimize.minimize(min_VaR, x0 = guesses,constraints = cons, bounds = bnds, args = (obj,))

In [32]:
pd.DataFrame(np.array([opt_weight3.x ,opt_weight4.x]).T, index = names_company, columns = ['Variance Weights', 'VaR Weights'])

                 Variance Weights   VaR Weights
AMER.EXPRESS         1.915959e-13  1.957323e-12
AOL TIME WARNER      1.000000e+00  1.000000e+00
AT & T               2.049459e-15  0.000000e+00
BLACK & DECKER       2.414195e-13  1.210563e-12
COLGATE - PALM.      1.570313e-14  1.034347e-12
FORD MOTOR           1.104013e-15  0.000000e+00
MCDONALDS            4.379926e-16  0.000000e+00
PFIZER               7.624219e-15  2.522348e-13
TEXAS INSTS.         5.375303e-13  0.000000e+00
WAL MART STORES      1.165455e-11  2.336963e-11